
x-common: &common
  restart: unless-stopped
  image: arkimage

x-clusters:
  - &nhcluster "newhorizon"

x-common-env: &common-env
  SOME_ENV: "yes"
  ARK_ServerPassword: "blub"
  ARKOPT_activeevent: "Summer"
  ARK_MaxPlayers: 60

services:
  webapi:
    image: hello-world

  updater:
    <<: *common
    restart: "no"
    command: update

  &instance test:
    image: arkimage
    build:
      dockerfile: instance.Dockerfile
    environment:
      INSTANCE_NAME: *instance
      OCC_ark_GameModIds: "123456789,987654321"
      OCC_ark_SessionName: "Zok's Generation IV - The Island"
      OCC_arkopt_clusterid: *nhcluster
      OCL_config_1: occ+bashlike:/etc/arkmanager/arkmanager.cfg?k=arkMaxBackupSizeMB&v=800
      OCL_config_2: occ+bashlike:/etc/arkmanager/arkmanager.cfg?k=arkprecisewarn&c
      

  &instance island:
    x-steamport: &steamport "27000:27000/udp"
    x-gameport: &gameport "17000:17000/udp"
    <<: *common
    ports: 
      - *steamport
      - *gameport
    <<: *common
    environment:
      STEAMPORT: *steamport
      GAMEPORT: *gameport
      INSTANCE_NAME: *instance
      MAP: "TheIsland"
      ARK_GameModIds: "123456789,987654321"
      ARK_SessionName: "Zok's Generation IV - The Island"
      ARKOPT_clusterid: *nhcluster
      <<: *common-env
    volumes:
      - "island:/ark/server/ShooterGame/Saved"
      - "gamefiles:/ark"
      - "backups:/arkbackups"

  &instance valguero:
    x-steamport: &steamport "27002:27002/udp"
    x-gameport: &gameport "17002:17002/udp"
    ports: 
      - *steamport
      - *gameport
    <<: *common
    environment:
      STEAMPORT: *steamport
      GAMEPORT: *gameport
      INSTANCE_NAME: *instance
      ARK_GameModIds: "123456789,987654321"
      <<: *common-env
    #volumes:
    #  <<: *common-volumes
  

volumes:
  gamefiles:
  backups:
  island: