
x-common: &common
  restart: "no"
  image: zokradonh/ark-server-docker
  build:
    dockerfile: instance.Dockerfile
  labels:
    - "xyz.zok.gsc=true"

x-clusters:
  - &nhcluster "newhorizon"

x-common-env: &common-env
  OCC_ark_ServerPassword: "asdf"
  OCC_arkopt_activeevent: "Summer"
  OCC_ark_MaxPlayers: 60
  OCC_arkflag_NoBattlEye: true

x-nh-env: &nh-env
  OCC_ark_GameModIds: "731604991"
  OCC_ark_SessionName: "Zok's Generation IV"
  OCC_arkopt_clusterid: *nhcluster

services:
  webapi:
    image: hello-world

  ftp:
    image: crazymax/pure-ftpd
    restart: unless-stopped
    ports:
      - "2100:2100"
      - "30000-30009:30000-30009"
    environment:
      - "TZ=Europe/Berlin"
      - "AUTH_METHOD=puredb"
    volumes:
      - "ftp:/data"
      - "gamefiles:/ark"
      - "island:/arks/island"
      - "valguero:/arks/valguero"

  updater:
    image: zokradonh/ark-server-docker
    build:
      dockerfile: instance.Dockerfile
    restart: "no"
    environment:
      UTILITY: "update"
    volumes:
      - "gamefiles:/ark"
    labels:
      - "xyz.zok.gsc.updater=true"

  &instance island:
    x-steamport: &steamport "27000:27000/udp"
    x-gameport: &gameport "17000:17000/udp"
    <<: *common
    ports: 
      - *steamport
      - *gameport
    environment:
      STEAMPORT: *steamport
      GAMEPORT: *gameport
      INSTANCE_NAME: *instance
      <<: *common-env
      <<: *nh-env
      OCC_serverMap: "TheIsland"
    volumes:
      - "gamefiles:/ark"
      - "island:/ark/server/ShooterGame/Saved"

  &instance valguero:
    x-steamport: &steamport "27002:27002/udp"
    x-gameport: &gameport "17002:17002/udp"
    <<: *common
    ports: 
      - *steamport
      - *gameport
    environment:
      STEAMPORT: *steamport
      GAMEPORT: *gameport
      INSTANCE_NAME: *instance
      <<: *common-env
      <<: *nh-env
      OCC_serverMap: "Valguero"
    volumes:
      - "gamefiles:/ark"
      - "valguero:/ark/server/ShooterGame/Saved"

volumes:
  ftp:
  gamefiles:
  island:
  valguero: