
x-common: &common
  restart: "no"
  image: zokradonh/ark-server-docker
  build:
    dockerfile: instance.Dockerfile

x-clusters:
  - &nhcluster "newhorizon"

x-common-env: &common-env
  OCC_ark_ServerPassword: "asdf"
  OCC_arkopt_activeevent: "Summer"
  OCC_ark_MaxPlayers: 60

services:
  webapi:
    image: hello-world

  updater:
    <<: *common
    restart: "no"
    environment:
      UTILITY: "update"
    volumes:
      - "gamefiles:/ark"
      - "backups:/arkbackups"

  &instance island:
    x-steamport: &steamport "27000:27000/udp"
    x-gameport: &gameport "17000:17000/udp"
    <<: *common
    ports: 
      - *steamport
      - *gameport
    <<: *common
    environment:
      STEAMPORT: *steamport
      GAMEPORT: *gameport
      INSTANCE_NAME: *instance
      OCC_serverMap: "TheIsland"
      OCC_ARK_GameModIds: "123456789,987654321"
      OCC_ARK_SessionName: "Zok's Generation IV - The Island"
      OCC_ARKOPT_clusterid: *nhcluster
      <<: *common-env
    volumes:
      - "island:/ark/server/ShooterGame/Saved"
      - "gamefiles:/ark"
      - "backups:/arkbackups"

  &instance valguero:
    x-steamport: &steamport "27002:27002/udp"
    x-gameport: &gameport "17002:17002/udp"
    <<: *common
    ports: 
      - *steamport
      - *gameport
    <<: *common
    environment:
      STEAMPORT: *steamport
      GAMEPORT: *gameport
      INSTANCE_NAME: *instance
      OCC_ARK_GameModIds: "123456789,987654321"
      OCC_ARK_SessionName: "Zok's Generation IV - Valguero"
      OCC_ARKOPT_clusterid: *nhcluster
      <<: *common-env
    volumes:
      - "valguero:/ark/server/ShooterGame/Saved"
      - "gamefiles:/ark"
      - "backups:/arkbackups"
  
volumes:
  gamefiles:
  backups:
  island:
  valguero: